---
kind: pipeline
type: kubernetes
name: default

steps:
- name: build & test
  image: mcr.microsoft.com/dotnet/sdk:3.1
  commands:
  - dotnet build
  - dotnet test
- name: build release
  when:
    event:
    - tag
  image: mcr.microsoft.com/dotnet/sdk:3.1
  commands:
  - dotnet build -c Release CrawlerPet911
  - dotnet publish -c Release CrawlerPet911
- name: build & push docker image
  when:
    event:
    - tag
  image: plugins/docker
  settings:
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    auto_tag: true
    repo: lostpetinitiative/crawler-pet911ru-agent