---
kind: pipeline
type: kubernetes
name: default

steps:
- name: build & test
  image: mcr.microsoft.com/dotnet/sdk:6.0
  commands:
  - dotnet build
  - dotnet test
- name: build & push docker image
  image: plugins/docker
  settings:
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    auto_tag: true
    repo: lostpetinitiative/crawler-pet911ru-agent
    force_tag: true